[std_coverage]

[no_std_coverage]
no-default-features = true

[serde_std_coverage]
features = "serde"

[serde_no_std_coverage]
no-default-features = true
features = "serde"

[sc_coverage]
features = "sc"

[report]
out = ["Html"]
